theme: jekyll-theme-slate

<!DOCTYPE html>
<title>Baking Fairy Cakes</title>

<p>Ingrediants:</p>
<ul>
  <li>125g butter</li>
  <li>125g caster sugar</li>
  <li>1tsp vanilla extract</li>
  <li>2 eggs</li>
  <li>150g plain flour</li>
  <li>¼ tsp baking powder</li>
</ul>

<p>To make a sponge cake, follow these steps:</p>

<ol>
  <li>Preheat the oven to 190°C. Line a 12-hole fairy cake tin.</li>
  <li>Cream the butter in a large bowl until soft.</li>
  <li>Add the sugar and vanilla extract and beat until the mixture is light and fluffy.</li>
  <li>Add the eggs, one at a time, beating continuously and sift the flour and baking powder.</li>
  <li>Divide the mixture evenly between the paper cases.</li>
  <li>Cook in the over for 8-12 mins or until golden brown and springy to the touch.</li>
  <li>Transfer the cakes to a wire rack to cool.<li>
  <li>When the cakes are completely cool, decorate them.<li>
</ol>
